
INSERT INTO parts (name, brand, price, stock, category, image_url)
VALUES ('Engine Oil Filter', 'Bosch', 12.99, 120, 'Engine', 'https://example.com/images/oil-filter.jpg'),
       ('Spark Plug Set', 'NGK', 24.50, 80, 'Engine', 'https://example.com/images/spark-plug.jpg'),
       ('Air Intake Hose', 'Denso', 35.00, 45, 'Engine', 'https://example.com/images/air-intake-hose.jpg'),
       ('Brake Pad Set Front', 'Brembo', 79.90, 60, 'Brakes', 'https://example.com/images/brake-pad.jpg'),
       ('Suspension Shock Absorber', 'KYB', 55.20, 95, 'Suspension', 'https://example.com/images/shock-absorber.jpg'),
       ('Car Battery 12V', 'Varta', 110.50, 30, 'Electrical', 'https://example.com/images/car-battery.jpg'),
       ('Wiper Blade Set', 'RainX', 18.75, 200, 'Exterior', 'https://example.com/images/wiper-blade.jpg'),
       ('Headlight Bulb H7', 'Philips', 8.99, 350, 'Lighting', 'https://example.com/images/headlight-bulb.jpg'),
       ('Cabin Air Filter', 'Mann', 15.40, 150, 'HVAC', 'https://example.com/images/cabin-filter.jpg'),
       ('Timing Belt Kit', 'Gates', 85.00, 40, 'Engine', 'https://example.com/images/timing-belt-kit.jpg'),
       ('Tire Pressure Sensor', 'Schrader', 29.95, 75, 'Tires', 'https://example.com/images/tpms.jpg'),
       ('Coolant Antifreeze', 'Prestone', 19.50, 110, 'Engine', 'https://example.com/images/coolant.jpg'),
       ('Alternator', 'Denso', 180.00, 25, 'Electrical', 'https://example.com/images/alternator.jpg'),
       ('Fuel Pump Module', 'Delphi', 95.80, 15, 'Fuel System', 'https://example.com/images/fuel-pump.jpg'),
       ('Ignition Coil', 'ACDelco', 38.00, 55, 'Engine', 'https://example.com/images/ignition-coil.jpg'),
       ('CV Axle Assembly', 'GSP', 65.99, 40, 'Drivetrain', 'https://example.com/images/cv-axle.jpg'),
       ('Wheel Bearing Kit', 'Moog', 42.10, 85, 'Suspension', 'https://example.com/images/wheel-bearing.jpg'),
       ('Thermostat Housing', 'Dorman', 22.00, 130, 'Engine', 'https://example.com/images/thermostat-housing.jpg'),
       ('Muffler Assembly', 'Walker', 150.75, 10, 'Exhaust', 'https://example.com/images/muffler.jpg'),
       ('Power Steering Pump', 'Luk', 135.00, 20, 'Steering', 'https://example.com/images/power-steering-pump.jpg'),
       ('Oxygen Sensor', 'Bosch', 49.99, 70, 'Exhaust', 'https://example.com/images/oxygen-sensor.jpg'),
       ('Tail Light Assembly', 'TYC', 75.50, 35, 'Lighting', 'https://example.com/images/tail-light.jpg'),
       ('Radiator', 'Spectra', 120.00, 28, 'Engine', 'https://example.com/images/radiator.jpg'),
       ('Clutch Kit', 'Sachs', 190.00, 12, 'Transmission', 'https://example.com/images/clutch-kit.jpg'),
       ('Serpentine Belt', 'Continental', 28.50, 180, 'Engine', 'https://example.com/images/serpentine-belt.jpg'),
       ('Ball Joint', 'ACDelco', 19.95, 90, 'Suspension', 'https://example.com/images/ball-joint.jpg'),
       ('Control Arm', 'Delphi', 60.25, 50, 'Suspension', 'https://example.com/images/control-arm.jpg'),
       ('Tie Rod End', 'Moog', 23.40, 115, 'Steering', 'https://example.com/images/tie-rod-end.jpg'),
       ('Water Pump', 'Airtex', 52.00, 65, 'Engine', 'https://example.com/images/water-pump.jpg'),
       ('Brake Rotor Front', 'StopTech', 88.00, 55, 'Brakes', 'https://example.com/images/brake-rotor.jpg'),
       ('Air Filter', 'K&N', 45.99, 140, 'Engine', 'https://example.com/images/air-filter.jpg'),
       ('Fuel Injector', 'Bosch', 72.50, 30, 'Fuel System', 'https://example.com/images/fuel-injector.jpg'),
       ('Transmission Filter Kit', 'Wix', 31.20, 70, 'Transmission', 'https://example.com/images/trans-filter.jpg'),
       ('Exhaust Manifold', 'Dorman', 160.00, 15, 'Exhaust', 'https://example.com/images/exhaust-manifold.jpg'),
       ('Starter Motor', 'Bosch', 145.00, 22, 'Electrical', 'https://example.com/images/starter-motor.jpg'),
       ('EGR Valve', 'Delphi', 58.75, 48, 'Emissions', 'https://example.com/images/egr-valve.jpg'),
       ('Heater Core', 'Four Seasons', 89.99, 18, 'HVAC', 'https://example.com/images/heater-core.jpg'),
       ('Wheel Hub Assembly', 'Timken', 70.45, 62, 'Suspension', 'https://example.com/images/wheel-hub.jpg'),
       ('Distributor Cap', 'Standard', 14.50, 150, 'Engine', 'https://example.com/images/distributor-cap.jpg'),
       ('Drive Belt Tensioner', 'Dayco', 33.99, 88, 'Engine', 'https://example.com/images/tensioner.jpg'),
       ('Throttle Body', 'Hitachi', 115.00, 20, 'Engine', 'https://example.com/images/throttle-body.jpg'),
       ('PCV Valve', 'Motorcraft', 7.90, 250, 'Emissions', 'https://example.com/images/pcv-valve.jpg'),
       ('Mass Air Flow Sensor', 'Denso', 88.00, 35, 'Engine', 'https://example.com/images/maf-sensor.jpg'),
       ('Brake Master Cylinder', 'Ate', 95.50, 40, 'Brakes', 'https://example.com/images/master-cylinder.jpg'),
       ('Rack and Pinion Assembly', 'ACDelco', 210.00, 10, 'Steering', 'https://example.com/images/rack-pinion.jpg'),
       ('Piston Ring Set', 'Mahle', 65.00, 30, 'Engine', 'https://example.com/images/piston-ring-set.jpg'),
       ('Head Gasket Set', 'Fel-Pro', 78.99, 45, 'Engine', 'https://example.com/images/head-gasket.jpg'),
       ('Camshaft Position Sensor', 'Standard', 32.75, 75, 'Engine', 'https://example.com/images/cam-sensor.jpg'),
       ('A/C Compressor', 'Denso', 250.00, 15, 'HVAC', 'https://example.com/images/ac-compressor.jpg'),
       ('Flasher Relay', 'Hella', 11.25, 190, 'Electrical', 'https://example.com/images/flasher-relay.jpg'),
       ('Door Handle Exterior', 'Dorman', 39.99, 50, 'Body', 'https://example.com/images/door-handle.jpg'),
       ('Mirror Assembly Side', 'TYC', 68.00, 30, 'Body', 'https://example.com/images/side-mirror.jpg'),
       ('Brake Drum Rear', 'Centric', 45.00, 65, 'Brakes', 'https://example.com/images/brake-drum.jpg'),
       ('Fuel Filter', 'Bosch', 14.99, 170, 'Fuel System', 'https://example.com/images/fuel-filter.jpg'),
       ('Oil Pan Gasket', 'Victor Reinz', 9.50, 120, 'Engine', 'https://example.com/images/oil-pan-gasket.jpg'),
       ('Oil Pressure Switch', 'Standard', 16.75, 90, 'Engine', 'https://example.com/images/oil-pressure-switch.jpg'),
       ('Power Window Regulator', 'Dorman', 55.99, 35, 'Electrical', 'https://example.com/images/window-regulator.jpg'),
       ('Glow Plug Set', 'Bosch', 40.00, 50, 'Engine', 'https://example.com/images/glow-plug-set.jpg'),
       ('Exhaust Gasket Set', 'Fel-Pro', 25.50, 70, 'Exhaust', 'https://example.com/images/exhaust-gasket.jpg'),
       ('Differential Seal Kit', 'Timken', 18.90, 80, 'Drivetrain', 'https://example.com/images/differential-seal.jpg'),
       ('Fuel Level Sensor', 'Delphi', 48.00, 25, 'Fuel System', 'https://example.com/images/fuel-level-sensor.jpg'),
       ('Heater Control Valve', 'Motorcraft', 30.75, 40, 'HVAC', 'https://example.com/images/heater-valve.jpg'),
       ('Wheel Cylinder Rear', 'Raybestos', 15.25, 100, 'Brakes', 'https://example.com/images/wheel-cylinder.jpg'),
       ('Windshield Washer Pump', 'Bosch', 9.99, 220, 'Exterior', 'https://example.com/images/washer-pump.jpg'),
       ('Horn Assembly', 'Hella', 16.50, 150, 'Electrical', 'https://example.com/images/horn-assembly.jpg'),
       ('Shock Mount', 'Moog', 27.90, 60, 'Suspension', 'https://example.com/images/shock-mount.jpg'),
       ('Idler Pulley', 'Gates', 12.45, 110, 'Engine', 'https://example.com/images/idler-pulley.jpg'),
       ('Crankshaft Position Sensor', 'ACDelco', 35.00, 70, 'Engine', 'https://example.com/images/crank-sensor.jpg'),
       ('Brake Caliper', 'A1 Cardone', 90.00, 30, 'Brakes', 'https://example.com/images/brake-caliper.jpg'),
       ('Control Arm Bushing', 'Febi', 14.20, 180, 'Suspension', 'https://example.com/images/control-arm-bushing.jpg'),
       ('Fuel Line Hose', 'Gates', 6.50, 300, 'Fuel System', 'https://example.com/images/fuel-line-hose.jpg'),
       ('Oil Cooler', 'Dorman', 79.99, 20, 'Engine', 'https://example.com/images/oil-cooler.jpg'),
       ('A/C Condenser', 'Denso', 150.00, 15, 'HVAC', 'https://example.com/images/ac-condenser.jpg'),
       ('Spark Plug Wire Set', 'Taylor', 32.90, 45, 'Engine', 'https://example.com/images/spark-plug-wire.jpg'),
       ('Headlight Assembly', 'TYC', 110.00, 25, 'Lighting', 'https://example.com/images/headlight-assembly.jpg'),
       ('Catalytic Converter', 'MagnaFlow', 350.00, 8, 'Exhaust', 'https://example.com/images/catalytic-converter.jpg'),
       ('Power Steering Fluid', 'Prestone', 8.50, 160, 'Steering', 'https://example.com/images/ps-fluid.jpg'),
       ('Engine Mount', 'Anchor', 45.00, 70, 'Engine', 'https://example.com/images/engine-mount.jpg'),
       ('Throttle Position Sensor', 'Hitachi', 40.50, 95, 'Engine', 'https://example.com/images/tps-sensor.jpg'),
       ('Brake Shoe Set Rear', 'Wagner', 28.00, 80, 'Brakes', 'https://example.com/images/brake-shoe.jpg'),
       ('EGR Cooler', 'Dorman', 190.00, 12, 'Emissions', 'https://example.com/images/egr-cooler.jpg'),
       ('Piston with Ring Set', 'Mahle', 85.99, 20, 'Engine', 'https://example.com/images/piston.jpg'),
       ('Flywheel', 'LuK', 120.00, 15, 'Transmission', 'https://example.com/images/flywheel.jpg'),
       ('Radiator Cap', 'Stant', 7.50, 210, 'Engine', 'https://example.com/images/radiator-cap.jpg'),
       ('Fuel Tank Strap', 'Dorman', 15.90, 90, 'Fuel System', 'https://example.com/images/fuel-tank-strap.jpg'),
       ('Blower Motor Resistor', 'Standard', 25.00, 75, 'HVAC', 'https://example.com/images/blower-resistor.jpg'),
       ('Fender Liner', 'TYC', 35.50, 40, 'Body', 'https://example.com/images/fender-liner.jpg'),
       ('Wiper Motor', 'ACDelco', 70.99, 30, 'Electrical', 'https://example.com/images/wiper-motor.jpg'),
       ('Engine Block Heater', 'Kat’s', 49.00, 25, 'Engine', 'https://example.com/images/block-heater.jpg'),
       ('Inner Tie Rod End', 'Moog', 28.50, 85, 'Steering', 'https://example.com/images/inner-tie-rod.jpg'),
       ('Sway Bar Link', 'TRW', 18.25, 150, 'Suspension', 'https://example.com/images/sway-bar-link.jpg'),
       ('Oil Filter Housing', 'Dorman', 55.00, 35, 'Engine', 'https://example.com/images/oil-filter-housing.jpg'),
       ('Brake Vacuum Pump', 'Bosch', 180.00, 10, 'Brakes', 'https://example.com/images/vacuum-pump.jpg'),
       ('Differential Bearing Kit', 'Timken', 65.00, 45, 'Drivetrain', 'https://example.com/images/diff-bearing.jpg'),
       ('Turbocharger', 'Garrett', 750.00, 5, 'Engine', 'https://example.com/images/turbocharger.jpg'),
       ('Intake Manifold Gasket', 'Fel-Pro', 16.99, 110, 'Engine', 'https://example.com/images/intake-gasket.jpg'),
       ('Transfer Case Motor', 'Dorman', 150.00, 18, 'Drivetrain',
        'https://example.com/images/transfer-case-motor.jpg'),
       ('Wiper Cowl Grille', 'TYC', 42.50, 30, 'Exterior', 'https://example.com/images/wiper-cowl.jpg'),
       ('HVAC Blend Door Actuator', 'ACDelco', 48.00, 60, 'HVAC', 'https://example.com/images/blend-door-actuator.jpg'),
       ('Fog Light Assembly', 'Depo', 45.99, 70, 'Lighting', 'https://example.com/images/fog-light.jpg'),
       ('Fuel Pressure Regulator', 'Standard', 38.20, 50, 'Fuel System',
        'https://example.com/images/f-pressure-regulator.jpg'),
       ('Engine Harmonic Balancer', 'Dorman', 60.00, 25, 'Engine', 'https://example.com/images/harmonic-balancer.jpg'),
       ('Hood Latch Cable', 'Dorman', 19.95, 120, 'Body', 'https://example.com/images/hood-latch-cable.jpg'),
       ('O2 Sensor Socket', 'Lisle', 12.00, 100, 'Tools', 'https://example.com/images/o2-socket.jpg'),
       ('Brake Fluid DOT 4', 'ATE', 16.50, 250, 'Brakes', 'https://example.com/images/brake-fluid.jpg'),
       ('Oil Drain Plug Gasket', 'Victor Reinz', 1.50, 500, 'Engine',
        'https://example.com/images/drain-plug-gasket.jpg'),
       ('Water Outlet Assembly', 'Dorman', 33.00, 65, 'Engine', 'https://example.com/images/water-outlet.jpg'),
       ('Transmission Oil Cooler', 'Hayden', 55.99, 30, 'Transmission', 'https://example.com/images/trans-cooler.jpg'),
       ('ABS Wheel Speed Sensor', 'Bosch', 45.00, 80, 'Brakes', 'https://example.com/images/abs-sensor.jpg'),
       ('Bumper Cover Front', 'TYC', 90.00, 20, 'Body', 'https://example.com/images/bumper-cover.jpg'),
       ('License Plate Light', 'Sylvania', 5.99, 150, 'Lighting', 'https://example.com/images/license-light.jpg'),
       ('Engine VVT Solenoid', 'Standard', 42.10, 55, 'Engine', 'https://example.com/images/vvt-solenoid.jpg'),
       ('Intake Valve', 'Mahle', 15.00, 200, 'Engine', 'https://example.com/images/intake-valve.jpg'),
       ('Exhaust Pipe Flange Gasket', 'Fel-Pro', 7.20, 180, 'Exhaust',
        'https://example.com/images/exhaust-flange-gasket.jpg'),
       ('Spark Plug Anti-Seize', 'Permatex', 4.99, 100, 'Chemicals', 'https://example.com/images/anti-seize.jpg'),
       ('Fuel Rail Pressure Sensor', 'Bosch', 78.50, 40, 'Fuel System',
        'https://example.com/images/fuel-rail-sensor.jpg'),
       ('Suspension Coil Spring', 'ACDelco', 65.00, 45, 'Suspension', 'https://example.com/images/coil-spring.jpg'),
       ('Brake Line Tubing', 'NiCopp', 1.50, 500, 'Brakes', 'https://example.com/images/brake-line-tubing.jpg'),
       ('EGR Tube', 'Dorman', 35.00, 60, 'Emissions', 'https://example.com/images/egr-tube.jpg'),
       ('A/C Accumulator/Drier', 'Four Seasons', 45.99, 30, 'HVAC', 'https://example.com/images/ac-drier.jpg'),
       ('Ignition Lock Cylinder', 'Standard', 39.00, 50, 'Electrical', 'https://example.com/images/ignition-lock.jpg'),
       ('Engine Oil 5W-30 (Quart)', 'Mobil 1', 7.99, 300, 'Oil & Fluids', 'https://example.com/images/engine-oil.jpg'),
       ('Power Steering Cooler', 'Hayden', 45.00, 25, 'Steering', 'https://example.com/images/ps-cooler.jpg'),
       ('Door Lock Actuator', 'Dorman', 60.50, 35, 'Body', 'https://example.com/images/door-lock-actuator.jpg'),
       ('License Plate Frame', 'Pilot', 9.99, 200, 'Accessories', 'https://example.com/images/license-frame.jpg'),
       ('Timing Chain Kit', 'Cloyes', 150.00, 15, 'Engine', 'https://example.com/images/timing-chain-kit.jpg'),
       ('Oil Catch Can', 'Mishimoto', 89.95, 20, 'Engine', 'https://example.com/images/oil-catch-can.jpg'),
       ('Wiper Blade Refill', 'Bosch', 6.50, 400, 'Exterior', 'https://example.com/images/wiper-refill.jpg'),
       ('Transmission Mount', 'Anchor', 38.00, 70, 'Transmission', 'https://example.com/images/trans-mount.jpg'),
       ('Spark Plug Gap Tool', 'KD Tools', 4.50, 150, 'Tools', 'https://example.com/images/spark-gap-tool.jpg'),
       ('Valve Cover Gasket Set', 'Victor Reinz', 22.90, 80, 'Engine',
        'https://example.com/images/valve-cover-gasket.jpg'),
       ('Tire Inflator Portable', 'Slime', 35.00, 40, 'Tires', 'https://example.com/images/tire-inflator.jpg'),
       ('Brake Cleaner Spray', 'CRC', 5.99, 300, 'Chemicals', 'https://example.com/images/brake-cleaner.jpg'),
       ('MAP Sensor', 'Denso', 55.00, 60, 'Engine', 'https://example.com/images/map-sensor.jpg'),
       ('Radiator Hose Upper', 'Gates', 18.00, 100, 'Engine', 'https://example.com/images/radiator-hose-upper.jpg'),
       ('Exhaust Hanger', 'Anchor', 8.50, 250, 'Exhaust', 'https://example.com/images/exhaust-hanger.jpg'),
       ('CV Boot Kit', 'GSP', 15.99, 90, 'Drivetrain', 'https://example.com/images/cv-boot-kit.jpg'),
       ('Heater Hose Connector', 'Dorman', 9.20, 130, 'HVAC', 'https://example.com/images/heater-hose-connector.jpg'),
       ('Stop Light Switch', 'Standard', 14.50, 110, 'Electrical', 'https://example.com/images/stop-light-switch.jpg'),
       ('Brake Pad Sensor', 'Bosch', 19.00, 70, 'Brakes', 'https://example.com/images/brake-pad-sensor.jpg'),
       ('Door Mirror Glass', 'TYC', 22.50, 40, 'Body', 'https://example.com/images/mirror-glass.jpg'),
       ('Headlight Switch', 'ACDelco', 55.00, 30, 'Lighting', 'https://example.com/images/headlight-switch.jpg'),
       ('Fuel Pump Relay', 'Hella', 12.75, 80, 'Fuel System', 'https://example.com/images/fuel-pump-relay.jpg'),
       ('Engine Detailing Spray', 'Chemical Guys', 15.00, 60, 'Chemicals',
        'https://example.com/images/engine-detailer.jpg'),
       ('Steering Wheel Cover', 'Budge', 25.99, 50, 'Interior', 'https://example.com/images/steering-cover.jpg'),
       ('Oil Filter Wrench', 'Lisle', 9.99, 90, 'Tools', 'https://example.com/images/oil-wrench.jpg'),
       ('Suspension Air Spring', 'Arnott', 250.00, 10, 'Suspension', 'https://example.com/images/air-spring.jpg'),
       ('Battery Terminal Cleaner', 'CRC', 3.50, 200, 'Chemicals', 'https://example.com/images/battery-cleaner.jpg'),
       ('Radiator Fan Motor', 'Dorman', 75.00, 25, 'Engine', 'https://example.com/images/radiator-fan-motor.jpg'),
       ('EGR Solenoid', 'Standard', 38.90, 45, 'Emissions', 'https://example.com/images/egr-solenoid.jpg'),
       ('Floor Mats All-Weather', 'WeatherTech', 150.00, 30, 'Interior', 'https://example.com/images/floor-mats.jpg'),
       ('Wheel Lug Nut Set', 'Gorilla', 29.99, 70, 'Tires', 'https://example.com/images/lug-nut-set.jpg'),
       ('Axle Shaft Seal', 'National', 10.50, 110, 'Drivetrain', 'https://example.com/images/axle-seal.jpg'),
       ('Brake Bleeder Kit', 'Motive', 65.00, 35, 'Tools', 'https://example.com/images/bleeder-kit.jpg'),
       ('Tire Valve Stem Caps', 'Pilot', 5.00, 300, 'Accessories', 'https://example.com/images/valve-caps.jpg'),
       ('License Plate Bracket', 'Dorman', 15.00, 150, 'Body', 'https://example.com/images/license-bracket.jpg'),
       ('Washer Fluid Concentrate', 'Prestone', 8.99, 250, 'Oil & Fluids',
        'https://example.com/images/washer-fluid.jpg'),
       ('Hood Prop Rod Clip', 'Dorman', 2.50, 400, 'Body', 'https://example.com/images/hood-clip.jpg'),
       ('Windshield Repair Kit', 'Permatex', 19.99, 60, 'Chemicals',
        'https://example.com/images/windshield-repair.jpg'),
       ('Cabin Air Filter Tool', 'Assenmacher', 25.00, 50, 'Tools', 'https://example.com/images/cabin-tool.jpg'),
       ('Battery Hold Down Clamp', 'Anchor', 11.50, 90, 'Electrical', 'https://example.com/images/battery-clamp.jpg'),
       ('Steering Column Bushing', 'Moog', 9.90, 120, 'Steering', 'https://example.com/images/steer-bushing.jpg'),
       ('Tailpipe Tip Chrome', 'Flowmaster', 45.00, 30, 'Exhaust', 'https://example.com/images/tailpipe-tip.jpg'),
       ('Fuel Filler Neck', 'Dorman', 68.00, 20, 'Fuel System', 'https://example.com/images/fuel-filler-neck.jpg'),
       ('Transmission Fluid ATF', 'Castrol', 6.99, 180, 'Oil & Fluids', 'https://example.com/images/atf-fluid.jpg'),
       ('Suspension Strut Assembly', 'Monroe', 110.00, 40, 'Suspension',
        'https://example.com/images/strut-assembly.jpg'),
       ('Brake Rotor Rear', 'Centric', 55.99, 75, 'Brakes', 'https://example.com/images/brake-rotor-rear.jpg'),
       ('Gasket Maker Silicone', 'Permatex', 8.50, 100, 'Chemicals', 'https://example.com/images/gasket-maker.jpg'),
       ('Coolant Temperature Sensor', 'Standard', 19.95, 110, 'Engine', 'https://example.com/images/temp-sensor.jpg'),
       ('Windshield Trim Molding', 'Dorman', 28.00, 50, 'Exterior', 'https://example.com/images/windshield-trim.jpg'),
       ('Door Check Strap', 'Dorman', 15.00, 70, 'Body', 'https://example.com/images/door-check-strap.jpg'),
       ('Engine Oil Pan', 'Spectra', 95.00, 25, 'Engine', 'https://example.com/images/oil-pan.jpg'),
       ('Starter Solenoid', 'ACDelco', 30.00, 60, 'Electrical', 'https://example.com/images/starter-solenoid.jpg'),
       ('Hose Clamp Assortment', 'Murray', 19.99, 45, 'Tools', 'https://example.com/images/hose-clamp.jpg'),
       ('Tire Sealant and Inflator', 'Slime', 12.50, 80, 'Tires', 'https://example.com/images/tire-sealant.jpg'),
       ('Universal Joint', 'Spicer', 28.90, 95, 'Drivetrain', 'https://example.com/images/universal-joint.jpg'),
       ('Power Steering Hose', 'Gates', 45.00, 35, 'Steering', 'https://example.com/images/ps-hose.jpg'),
       ('Vacuum Pump Gasket', 'Victor Reinz', 5.99, 150, 'Engine', 'https://example.com/images/vacuum-pump-gasket.jpg'),
       ('A/C Service Port Cap', 'Four Seasons', 4.50, 200, 'HVAC', 'https://example.com/images/ac-cap.jpg'),
       ('Head Gasket Sealant', 'K&W', 29.99, 40, 'Chemicals', 'https://example.com/images/head-gasket-sealant.jpg'),
       ('Bumper Grille', 'TYC', 35.00, 50, 'Body', 'https://example.com/images/bumper-grille.jpg'),
       ('Taillight Bulb', 'Sylvania', 3.99, 300, 'Lighting', 'https://example.com/images/taillight-bulb.jpg'),
       ('Engine Control Unit (ECU)', 'Bosch', 450.00, 5, 'Electrical', 'https://example.com/images/ecu.jpg'),
       ('Muffler Clamp', 'Walker', 6.50, 180, 'Exhaust', 'https://example.com/images/muffler-clamp.jpg'),
       ('Fuel Tank Sending Unit', 'Delphi', 85.00, 20, 'Fuel System',
        'https://example.com/images/fuel-sending-unit.jpg'),
       ('Oil Filler Cap', 'Dorman', 8.90, 130, 'Engine', 'https://example.com/images/oil-filler-cap.jpg'),
       ('Brake Pad Set Rear', 'Brembo', 65.00, 55, 'Brakes', 'https://example.com/images/brake-pad-rear.jpg'),
       ('Car Cover Outdoor', 'Coverking', 99.99, 30, 'Accessories', 'https://example.com/images/car-cover.jpg'),
       ('Steering Damper', 'KYB', 50.00, 40, 'Steering', 'https://example.com/images/steering-damper.jpg'),
       ('Brake Bleeder Screw', 'Dorman', 3.50, 250, 'Brakes', 'https://example.com/images/bleeder-screw.jpg'),
       ('Engine Air Duct', 'Dorman', 22.00, 70, 'Engine', 'https://example.com/images/air-duct.jpg'),
       ('Wiper Linkage Assembly', 'ACDelco', 55.99, 35, 'Exterior', 'https://example.com/images/wiper-linkage.jpg'),
       ('Ignition Relay', 'Hella', 10.50, 120, 'Electrical', 'https://example.com/images/ignition-relay.jpg'),
       ('Coil Over Shock', 'Monroe', 130.00, 20, 'Suspension', 'https://example.com/images/coil-over-shock.jpg'),
       ('Exhaust Flange Bolt', 'Walker', 4.99, 300, 'Exhaust', 'https://example.com/images/exhaust-bolt.jpg'),
       ('A/C Orifice Tube', 'Four Seasons', 6.90, 150, 'HVAC', 'https://example.com/images/orifice-tube.jpg'),
       ('License Plate Light Housing', 'TYC', 12.00, 90, 'Lighting', 'https://example.com/images/license-housing.jpg'),
       ('Fuel Injector Seal Kit', 'Bosch', 18.00, 100, 'Fuel System',
        'https://example.com/images/injector-seal-kit.jpg'),
       ('Oil Dipstick Tube', 'Dorman', 15.50, 80, 'Engine', 'https://example.com/images/dipstick-tube.jpg'),
       ('Glove Box Latch', 'Dorman', 10.99, 110, 'Interior', 'https://example.com/images/glove-box-latch.jpg'),
       ('Jack Stand Pair', 'Torin', 45.00, 60, 'Tools', 'https://example.com/images/jack-stand.jpg'),
       ('Wheel Spacer Kit', 'Eibach', 85.00, 25, 'Tires', 'https://example.com/images/wheel-spacer.jpg'),
       ('Car Wax Liquid', 'Meguiar’s', 19.99, 70, 'Chemicals', 'https://example.com/images/car-wax.jpg'),
       ('Throttle Cable', 'Dorman', 28.00, 50, 'Engine', 'https://example.com/images/throttle-cable.jpg'),
       ('PCV Hose', 'Gates', 9.50, 150, 'Engine', 'https://example.com/images/pcv-hose.jpg'),
       ('Brake Line Fitting', 'Dorman', 2.00, 400, 'Brakes', 'https://example.com/images/brake-fitting.jpg'),
       ('Differential Gasket', 'Fel-Pro', 12.00, 100, 'Drivetrain', 'https://example.com/images/diff-gasket.jpg'),
       ('Brake Rotor Drill/Slot', 'StopTech', 120.00, 40, 'Brakes', 'https://example.com/images/drilled-rotor.jpg'),
       ('Wiper Fluid Reservoir', 'TYC', 30.50, 35, 'Exterior', 'https://example.com/images/fluid-reservoir.jpg'),
       ('Door Handle Interior', 'Dorman', 25.00, 60, 'Interior', 'https://example.com/images/door-handle-int.jpg'),
       ('A/C Refrigerant Can', 'R-134a', 14.99, 100, 'Chemicals', 'https://example.com/images/refrigerant.jpg'),
       ('Engine Timing Cover', 'Dorman', 55.00, 25, 'Engine', 'https://example.com/images/timing-cover.jpg'),
       ('Fuel Filler Cap', 'Stant', 10.50, 120, 'Fuel System', 'https://example.com/images/fuel-filler-cap.jpg'),
       ('Dome Light Bulb LED', 'Sylvania', 8.99, 150, 'Lighting', 'https://example.com/images/dome-light-led.jpg'),
       ('Serpentine Belt Tool', 'Lisle', 45.00, 70, 'Tools', 'https://example.com/images/belt-tool.jpg'),
       ('Strut Mount Bearing', 'ACDelco', 20.00, 90, 'Suspension', 'https://example.com/images/strut-bearing.jpg'),
       ('Exhaust System Cat-Back', 'Flowmaster', 450.00, 10, 'Exhaust',
        'https://example.com/images/cat-back-exhaust.jpg'),
       ('Heater Core Gasket', 'Fel-Pro', 7.50, 110, 'HVAC', 'https://example.com/images/heater-core-gasket.jpg'),
       ('Steering Knuckle', 'Moog', 95.00, 30, 'Steering', 'https://example.com/images/steering-knuckle.jpg'),
       ('Battery Jumper Cables', 'BoostAll', 25.99, 40, 'Electrical', 'https://example.com/images/jumper-cables.jpg'),
       ('Brake Pedal Pad', 'Dorman', 5.90, 200, 'Interior', 'https://example.com/images/brake-pedal-pad.jpg'),
       ('Valve Stem Seal Set', 'Mahle', 15.00, 80, 'Engine', 'https://example.com/images/valve-stem-seal.jpg'),
       ('Tire Gauge Digital', 'Michelin', 12.99, 130, 'Tires', 'https://example.com/images/tire-gauge.jpg'),
       ('Body Side Molding', 'Dorman', 40.00, 45, 'Body', 'https://example.com/images/side-molding.jpg'),
       ('Oil Filter Cartridge', 'Mann', 10.50, 160, 'Engine', 'https://example.com/images/oil-filter-cartridge.jpg'),
       ('Fuel Pump Strainer', 'Bosch', 8.90, 90, 'Fuel System', 'https://example.com/images/fuel-strainer.jpg'),
       ('CV Axle Bolt', 'Dorman', 3.00, 350, 'Drivetrain', 'https://example.com/images/cv-axle-bolt.jpg'),
       ('Coolant Flush Kit', 'Prestone', 15.99, 50, 'Chemicals', 'https://example.com/images/coolant-flush-kit.jpg'),
       ('A/C Expansion Valve', 'Denso', 55.00, 30, 'HVAC', 'https://example.com/images/expansion-valve.jpg'),
       ('Brake Hardware Kit', 'Raybestos', 14.50, 110, 'Brakes', 'https://example.com/images/brake-hardware-kit.jpg'),
       ('Headlight Bulb LED Conversion', 'Sylvania', 85.00, 20, 'Lighting',
        'https://example.com/images/led-conversion.jpg'),
       ('Radiator Drain Cock', 'Dorman', 6.99, 180, 'Engine', 'https://example.com/images/drain-cock.jpg'),
       ('Alternator Pulley', 'INA', 25.00, 70, 'Electrical', 'https://example.com/images/alternator-pulley.jpg'),
       ('EGR Gasket', 'Fel-Pro', 5.50, 220, 'Emissions', 'https://example.com/images/egr-gasket.jpg'),
       ('Floor Jack Hydraulic 3 Ton', 'Arcan', 120.00, 15, 'Tools', 'https://example.com/images/floor-jack.jpg'),
       ('Wheel Lock Set', 'McGard', 35.00, 60, 'Tires', 'https://example.com/images/wheel-lock.jpg'),
       ('Differential Fluid 75W-90', 'Mobil 1', 18.99, 95, 'Oil & Fluids', 'https://example.com/images/diff-fluid.jpg'),
       ('Door Weatherstrip Seal', 'Precision', 45.00, 40, 'Body', 'https://example.com/images/door-weatherstrip.jpg'),
       ('Engine Air Filter Housing', 'Dorman', 60.00, 25, 'Engine',
        'https://example.com/images/air-filter-housing.jpg'),
       ('Power Window Switch', 'Standard', 48.00, 55, 'Electrical', 'https://example.com/images/window-switch.jpg'),
       ('Oil Separator', 'Mann', 30.50, 75, 'Engine', 'https://example.com/images/oil-separator.jpg'),
       ('Exhaust Manifold Stud', 'Dorman', 3.99, 300, 'Exhaust', 'https://example.com/images/manifold-stud.jpg'),
       ('Steering Rack Boot', 'Moog', 15.00, 110, 'Steering', 'https://example.com/images/steering-boot.jpg'),
       ('License Plate Frame Slim', 'Pilot', 12.00, 180, 'Accessories', 'https://example.com/images/slim-frame.jpg'),
       ('A/C Manifold Gauge Set', 'Yellow Jacket', 190.00, 10, 'Tools', 'https://example.com/images/ac-gauge-set.jpg'),
       ('Fuel Tank Vent Valve', 'Delphi', 40.00, 45, 'Fuel System', 'https://example.com/images/vent-valve.jpg'),
       ('Brake Pad Wear Indicator', 'Bosch', 15.99, 90, 'Brakes', 'https://example.com/images/wear-indicator.jpg'),
       ('Engine Degreaser Spray', 'Gunk', 6.99, 140, 'Chemicals', 'https://example.com/images/engine-degreaser.jpg'),
       ('Suspension Ball Joint Boot', 'Moog', 7.50, 200, 'Suspension',
        'https://example.com/images/ball-joint-boot.jpg'),
       ('Tailgate Handle', 'Dorman', 35.00, 30, 'Body', 'https://example.com/images/tailgate-handle.jpg'),
       ('Heater Blower Motor', 'ACDelco', 65.00, 35, 'HVAC', 'https://example.com/images/blower-motor.jpg'),
       ('Door Lock Cylinder', 'Standard', 22.90, 80, 'Interior', 'https://example.com/images/door-lock-cylinder.jpg'),
       ('Oil Pressure Sender', 'VDO', 33.00, 65, 'Engine', 'https://example.com/images/oil-pressure-sender.jpg'),
       ('Coolant Reservoir Tank', 'TYC', 45.99, 25, 'Engine', 'https://example.com/images/coolant-tank.jpg'),
       ('Exhaust Oxygen Sensor Spacer', 'Blox Racing', 15.00, 100, 'Exhaust',
        'https://example.com/images/o2-spacer.jpg'),
       ('CV Axle Nut', 'Dorman', 4.50, 400, 'Drivetrain', 'https://example.com/images/cv-axle-nut.jpg'),
       ('Brake Caliper Piston Tool', 'CTA Tools', 28.00, 50, 'Tools', 'https://example.com/images/caliper-tool.jpg'),
       ('Fender Flare Set', 'Bushwacker', 250.00, 10, 'Body', 'https://example.com/images/fender-flare.jpg'),
       ('Glow Plug Relay', 'Standard', 48.99, 40, 'Electrical', 'https://example.com/images/glow-plug-relay.jpg'),
       ('Fuel Injector O-Ring Kit', 'Bosch', 10.50, 150, 'Fuel System',
        'https://example.com/images/injector-o-ring.jpg'),
       ('Headlight Bulb Xenon D2S', 'Osram', 80.00, 30, 'Lighting', 'https://example.com/images/xenon-bulb.jpg'),
       ('Transmission Pan Gasket', 'Fel-Pro', 18.00, 90, 'Transmission',
        'https://example.com/images/trans-pan-gasket.jpg'),
       ('Engine Coolant Sensor Connector', 'Dorman', 12.00, 120, 'Engine',
        'https://example.com/images/coolant-connector.jpg'),
       ('Tire Valve Stem', 'Schrader', 2.50, 500, 'Tires', 'https://example.com/images/valve-stem.jpg'),
       ('Battery Charger Portable', 'NOCO', 75.00, 25, 'Electrical', 'https://example.com/images/battery-charger.jpg'),
       ('Power Steering Rack Seal Kit', 'Edelmann', 22.99, 70, 'Steering',
        'https://example.com/images/rack-seal-kit.jpg'),
       ('Wiper Blade Winter', 'Bosch', 15.00, 100, 'Exterior', 'https://example.com/images/winter-wiper.jpg'),
       ('Radiator Hose Lower', 'Gates', 22.50, 80, 'Engine', 'https://example.com/images/radiator-hose-lower.jpg'),
       ('Brake Caliper Bolt', 'Dorman', 4.50, 300, 'Brakes', 'https://example.com/images/caliper-bolt.jpg'),
       ('Air Bag Clock Spring', 'Dorman', 95.00, 20, 'Electrical', 'https://example.com/images/clock-spring.jpg'),
       ('Suspension Strut Boot', 'KYB', 12.00, 150, 'Suspension', 'https://example.com/images/strut-boot.jpg'),
       ('Exhaust Clamp U-Bolt', 'Walker', 5.99, 250, 'Exhaust', 'https://example.com/images/u-bolt-clamp.jpg'),
       ('Gasket Scraper Tool', 'Lisle', 8.50, 110, 'Tools', 'https://example.com/images/gasket-scraper.jpg'),
       ('Hood Release Handle', 'Dorman', 10.99, 90, 'Body', 'https://example.com/images/hood-handle.jpg'),
       ('A/C Compressor Clutch', 'Denso', 70.00, 30, 'HVAC', 'https://example.com/images/ac-clutch.jpg'),
       ('Fuel Pump Lock Ring Tool', 'CTA Tools', 35.00, 40, 'Tools', 'https://example.com/images/lock-ring-tool.jpg'),
       ('Engine Oil 0W-20 (Quart)', 'Castrol', 8.99, 280, 'Oil & Fluids',
        'https://example.com/images/engine-oil-0w20.jpg'),
       ('Bumper Reflector', 'TYC', 18.50, 70, 'Lighting', 'https://example.com/images/bumper-reflector.jpg'),
       ('Ignition Switch Actuator Pin', 'Dorman', 15.00, 100, 'Electrical',
        'https://example.com/images/actuator-pin.jpg'),
       ('Tire Repair Plug Kit', 'Slime', 10.99, 120, 'Tires', 'https://example.com/images/tire-plug-kit.jpg'),
       ('Wheel Hub Dust Cap', 'Dorman', 6.50, 180, 'Drivetrain', 'https://example.com/images/dust-cap.jpg'),
       ('Car Wash Soap', 'Meguiar’s', 12.00, 200, 'Chemicals', 'https://example.com/images/car-wash-soap.jpg'),
       ('Radiator Fan Shroud', 'TYC', 55.00, 20, 'Engine', 'https://example.com/images/fan-shroud.jpg'),
       ('Door Trim Panel Clip', 'Dorman', 4.00, 500, 'Interior', 'https://example.com/images/trim-clip.jpg'),
       ('Fuel Line Quick Connector', 'Dorman', 11.50, 150, 'Fuel System',
        'https://example.com/images/quick-connector.jpg'),
       ('Brake Anti-Squeal Paste', 'Permatex', 7.99, 100, 'Chemicals',
        'https://example.com/images/anti-squeal-paste.jpg'),
       ('Suspension Trailing Arm', 'Moog', 75.00, 30, 'Suspension', 'https://example.com/images/trailing-arm.jpg'),
       ('Headlight Lens Repair Kit', '3M', 25.00, 45, 'Lighting', 'https://example.com/images/lens-repair-kit.jpg'),
       ('Engine Valve Lifter', 'Mahle', 18.00, 95, 'Engine', 'https://example.com/images/valve-lifter.jpg'),
       ('Oil Filter Sealing Ring', 'Bosch', 1.99, 300, 'Engine', 'https://example.com/images/sealing-ring.jpg'),
       ('Exhaust Resonator Assembly', 'Walker', 85.00, 15, 'Exhaust', 'https://example.com/images/resonator.jpg'),
       ('HVAC Temperature Actuator', 'ACDelco', 40.00, 60, 'HVAC', 'https://example.com/images/temp-actuator.jpg'),
       ('Power Steering Pump Reservoir', 'Dorman', 25.00, 70, 'Steering',
        'https://example.com/images/ps-reservoir.jpg'),
       ('Transmission Oil Pump', 'ACDelco', 150.00, 12, 'Transmission',
        'https://example.com/images/trans-oil-pump.jpg'),
       ('Fuel Tank Sealer', 'Permatex', 29.99, 40, 'Chemicals', 'https://example.com/images/fuel-tank-sealer.jpg'),
       ('Engine Timing Belt Tensioner', 'INA', 45.00, 50, 'Engine', 'https://example.com/images/belt-tensioner.jpg'),
       ('Door Handle Gasket Set', 'Dorman', 8.50, 130, 'Body', 'https://example.com/images/door-handle-gasket.jpg'),
       ('Brake Line Flaring Tool', 'Powerbuilt', 55.00, 25, 'Tools', 'https://example.com/images/flaring-tool.jpg'),
       ('Tire Changer Mount/Demount Head', 'Corghi', 120.00, 10, 'Tools',
        'https://example.com/images/changer-head.jpg'),
       ('Wheel Bolt Set', 'Febi', 18.99, 80, 'Tires', 'https://example.com/images/wheel-bolt-set.jpg'),
       ('Headlight Bulb Hi/Lo Beam', 'Sylvania', 15.00, 100, 'Lighting', 'https://example.com/images/hi-lo-bulb.jpg'),
       ('Oil Filter Magnet', 'MagnaDrain', 19.99, 65, 'Engine', 'https://example.com/images/oil-magnet.jpg'),
       ('Engine Coolant Temperature Switch', 'Standard', 17.50, 110, 'Engine',
        'https://example.com/images/temp-switch.jpg'),
       ('Exhaust System Gasket & Sealant Kit', 'Fel-Pro', 35.00, 45, 'Exhaust',
        'https://example.com/images/exhaust-kit.jpg'),
       ('Differential Pinion Seal', 'Timken', 12.90, 90, 'Drivetrain', 'https://example.com/images/pinion-seal.jpg'),
       ('Brake Master Cylinder Reservoir', 'Dorman', 28.00, 55, 'Brakes',
        'https://example.com/images/mc-reservoir.jpg'),
       ('A/C Suction Hose', 'Continental', 70.00, 20, 'HVAC', 'https://example.com/images/ac-suction-hose.jpg'),
       ('Car Alarm System', 'Viper', 150.00, 15, 'Electrical', 'https://example.com/images/car-alarm.jpg'),
       ('Wiper Fluid Level Sensor', 'Standard', 16.99, 80, 'Exterior', 'https://example.com/images/wiper-sensor.jpg'),
       ('Seat Cover Universal', 'FH Group', 45.00, 60, 'Interior', 'https://example.com/images/seat-cover.jpg'),
       ('Fuel Pressure Test Kit', 'Lisle', 75.00, 30, 'Tools', 'https://example.com/images/fuel-test-kit.jpg'),
       ('Engine Gasket Set Full', 'Victor Reinz', 190.00, 10, 'Engine',
        'https://example.com/images/full-gasket-set.jpg'),
       ('Tie Rod End Adjusting Sleeve', 'Moog', 10.50, 140, 'Steering',
        'https://example.com/images/adjusting-sleeve.jpg'),
       ('Suspension Stabilizer Bar Bushing', 'Moog', 9.99, 250, 'Suspension',
        'https://example.com/images/stab-bar-bushing.jpg'),
       ('Tire Black Foam', 'Meguiar’s', 8.50, 180, 'Chemicals', 'https://example.com/images/tire-black-foam.jpg'),
       ('License Plate Relocation Kit', 'Sickspeed', 25.00, 75, 'Accessories',
        'https://example.com/images/relocation-kit.jpg'),
       ('Muffler Gasket', 'Fel-Pro', 4.00, 200, 'Exhaust', 'https://example.com/images/muffler-gasket.jpg'),
       ('Brake Light Bulb', 'Sylvania', 2.50, 400, 'Lighting', 'https://example.com/images/brake-light-bulb.jpg'),
       ('Brake Caliper Rebuild Kit', 'Centric', 18.00, 110, 'Brakes',
        'https://example.com/images/caliper-rebuild-kit.jpg'),
       ('A/C Condenser Fan Assembly', 'TYC', 110.00, 25, 'HVAC', 'https://example.com/images/condenser-fan.jpg'),
       ('Timing Chain Tensioner', 'Cloyes', 38.00, 50, 'Engine', 'https://example.com/images/chain-tensioner.jpg'),
       ('Transfer Case Fluid', 'Castrol', 15.00, 90, 'Oil & Fluids',
        'https://example.com/images/transfer-case-fluid.jpg'),
       ('Fuel Tank Filler Pipe', 'Dorman', 55.00, 30, 'Fuel System', 'https://example.com/images/filler-pipe.jpg'),
       ('Wiper Blade Rear', 'Bosch', 12.00, 150, 'Exterior', 'https://example.com/images/wiper-blade-rear.jpg'),
       ('Radiator Petcock', 'Dorman', 5.50, 220, 'Engine', 'https://example.com/images/radiator-petcock.jpg'),
       ('Engine Control Module (ECM) Relay', 'Hella', 15.00, 100, 'Electrical',
        'https://example.com/images/ecm-relay.jpg'),
       ('Door Hinge Pin and Bushing Kit', 'Dorman', 19.99, 70, 'Body', 'https://example.com/images/door-hinge-kit.jpg'),
       ('Oil Funnel No-Spill', 'Hopkins', 10.99, 130, 'Tools', 'https://example.com/images/oil-funnel.jpg'),
       ('Suspension Control Arm Kit', 'Delphi', 180.00, 15, 'Suspension',
        'https://example.com/images/control-arm-kit.jpg'),
       ('Exhaust Manifold Gasket Set', 'Fel-Pro', 28.00, 60, 'Exhaust',
        'https://example.com/images/manifold-gasket-set.jpg'),
       ('Steering Shaft U-Joint', 'Dorman', 45.00, 35, 'Steering', 'https://example.com/images/steering-u-joint.jpg'),
       ('Brake Drum Hardware Kit', 'Raybestos', 12.50, 95, 'Brakes',
        'https://example.com/images/drum-hardware-kit.jpg'),
       ('Tire Iron Lug Wrench', 'Torin', 14.99, 85, 'Tools', 'https://example.com/images/lug-wrench.jpg'),
       ('Car Air Freshener', 'Little Trees', 2.00, 500, 'Accessories', 'https://example.com/images/air-freshener.jpg'),
       ('Engine Valve Cover', 'Dorman', 65.00, 25, 'Engine', 'https://example.com/images/valve-cover.jpg'),
       ('Fuel Pump Lock Ring', 'Dorman', 15.90, 75, 'Fuel System', 'https://example.com/images/lock-ring.jpg'),
       ('Wheel Weight Tape', '3M', 18.00, 100, 'Tires', 'https://example.com/images/wheel-weight-tape.jpg'),
       ('A/C Blower Motor Fan Cage', 'ACDelco', 35.00, 40, 'HVAC', 'https://example.com/images/fan-cage.jpg'),
       ('Bumper Fascia Retainer', 'Dorman', 1.50, 400, 'Body', 'https://example://example.com/images/retainer.jpg'),
       ('Turn Signal Light Assembly', 'TYC', 38.00, 55, 'Lighting',
        'https://example.com/images/turn-signal-assembly.jpg'),
       ('Engine Coolant Additive', 'Water Wetter', 12.99, 110, 'Chemicals',
        'https://example.com/images/coolant-additive.jpg'),
       ('Crankshaft Main Bearing Set', 'Mahle', 40.00, 60, 'Engine', 'https://example.com/images/main-bearing.jpg'),
       ('Transmission Shift Cable', 'Dorman', 48.00, 30, 'Transmission', 'https://example.com/images/shift-cable.jpg'),
       ('Head Gasket Set with Bolts', 'Fel-Pro', 120.00, 20, 'Engine',
        'https://example.com/images/gasket-set-w-bolts.jpg'),
       ('Brake Hose Front', 'ACDelco', 18.95, 80, 'Brakes', 'https://example.com/images/brake-hose-front.jpg'),
       ('Ignition Coil Boot', 'Bosch', 5.50, 200, 'Engine', 'https://example.com/images/coil-boot.jpg'),
       ('Power Steering Pump Pulley', 'Dorman', 20.00, 90, 'Steering', 'https://example.com/images/ps-pulley.jpg'),
       ('Wiper Blade All Season', 'Trico', 15.99, 150, 'Exterior', 'https://example.com/images/all-season-wiper.jpg'),
       ('Exhaust Heat Shield', 'Dorman', 30.00, 70, 'Exhaust', 'https://example.com/images/heat-shield.jpg'),
       ('Oil Drain Pan', 'Rhino', 14.50, 100, 'Tools', 'https://example.com/images/drain-pan.jpg'),
       ('Suspension Coil Spring Insulator', 'Moog', 7.99, 180, 'Suspension',
        'https://example.com/images/coil-insulator.jpg'),
       ('Tire Valve Stem Tool', 'Slime', 3.00, 250, 'Tires', 'https://example.com/images/valve-stem-tool.jpg'),
       ('Brake Caliper Slide Pin', 'Dorman', 4.90, 300, 'Brakes', 'https://example.com/images/caliper-slide-pin.jpg'),
       ('Door Lock Knob', 'Dorman', 4.50, 150, 'Interior', 'https://example.com/images/door-lock-knob.jpg'),
       ('HVAC Heater Valve Vacuum Motor', 'ACDelco', 55.00, 35, 'HVAC', 'https://example.com/images/vacuum-motor.jpg'),
       ('Headlight Leveling Motor', 'Hella', 45.00, 40, 'Lighting', 'https://example.com/images/leveling-motor.jpg'),
       ('Fuel System Cleaner', 'Techron', 9.99, 120, 'Chemicals', 'https://example.com/images/fuel-cleaner.jpg'),
       ('Engine Water Bypass Hose', 'Gates', 8.90, 110, 'Engine', 'https://example.com/images/bypass-hose.jpg'),
       ('Crankshaft Seal Front', 'National', 6.99, 160, 'Engine', 'https://example.com/images/crankshaft-seal.jpg'),
       ('Differential Carrier Bearing', 'Timken', 25.00, 75, 'Drivetrain',
        'https://example.com/images/carrier-bearing.jpg'),
       ('Battery Isolator', 'Hellroaring', 60.00, 20, 'Electrical', 'https://example.com/images/battery-isolator.jpg'),
       ('License Plate Screws Stainless', 'Dorman', 4.50, 300, 'Accessories',
        'https://example.com/images/license-screws.jpg'),
       ('Muffler Clamp Bolt', 'Walker', 3.50, 400, 'Exhaust', 'https://example.com/images/muffler-clamp-bolt.jpg'),
       ('Transmission Shift Solenoid', 'Standard', 70.00, 30, 'Transmission',
        'https://example.com/images/shift-solenoid.jpg'),
       ('Brake Proportioning Valve', 'ACDelco', 95.00, 15, 'Brakes', 'https://example.com/images/prop-valve.jpg'),
       ('Door Window Channel Felt', 'Precision', 18.00, 90, 'Body', 'https://example.com/images/window-channel.jpg'),
       ('Oil Pressure Switch Connector', 'Dorman', 7.50, 150, 'Engine',
        'https://example.com/images/pressure-connector.jpg'),
       ('Radiator Mount Bushing', 'Dorman', 5.99, 200, 'Engine', 'https://example.com/images/radiator-bushing.jpg'),
       ('Wiper Arm Nut Cap', 'Dorman', 3.00, 350, 'Exterior', 'https://example.com/images/wiper-nut-cap.jpg'),
       ('Suspension Shock Boot', 'KYB', 9.99, 120, 'Suspension', 'https://example.com/images/shock-boot.jpg'),
       ('Steering Column Bearing', 'Moog', 15.00, 95, 'Steering',
        'https://example.com/images/steer-column-bearing.jpg'),
       ('Fuel Injector Cleaner Tool', 'Lisle', 60.00, 40, 'Tools',
        'https://example.com/images/injector-cleaner-tool.jpg'),
       ('Tire Mounting Paste', 'Ken-Tool', 12.00, 110, 'Chemicals', 'https://example.com/images/mounting-paste.jpg'),
       ('Engine Block Plug', 'Dorman', 5.00, 180, 'Engine', 'https://example.com/images/block-plug.jpg'),
       ('A/C Compressor Clutch Relay', 'Hella', 18.00, 70, 'Electrical',
        'https://example.com/images/ac-clutch-relay.jpg'),
       ('Brake Booster Vacuum Hose', 'Gates', 10.50, 130, 'Brakes', 'https://example.com/images/booster-hose.jpg'),
       ('Console Lid Armrest Cover', 'Dorman', 45.00, 30, 'Interior', 'https://example.com/images/console-cover.jpg'),
       ('Headlight Bulb H4', 'Philips', 9.99, 160, 'Lighting', 'https://example.com/images/headlight-bulb-h4.jpg'),
       ('Turbocharger Oil Feed Line', 'Dorman', 55.00, 20, 'Engine', 'https://example.com/images/turbo-oil-line.jpg'),
       ('Exhaust Flex Pipe', 'Walker', 40.00, 50, 'Exhaust', 'https://example.com/images/flex-pipe.jpg'),
       ('Fuel Pump Wiring Harness', 'Dorman', 28.00, 65, 'Fuel System',
        'https://example.com/images/fuel-pump-harness.jpg'),
       ('Suspension Strut Bellow', 'KYB', 8.50, 140, 'Suspension', 'https://example.com/images/strut-bellow.jpg'),
       ('Engine Oil 10W-40 (Quart)', 'Pennzoil', 6.50, 250, 'Oil & Fluids',
        'https://example.com/images/engine-oil-10w40.jpg'),
       ('Axle Shaft Retaining Ring', 'Dorman', 2.00, 300, 'Drivetrain',
        'https://example.com/images/retaining-ring.jpg'),
       ('Battery Terminal End Kit', 'Standard', 15.00, 100, 'Electrical',
        'https://example.com/images/terminal-kit.jpg'),
       ('Wheel Hub Grease Cap', 'Dorman', 3.50, 200, 'Tires', 'https://example.com/images/grease-cap.jpg'),
       ('Steering Tie Rod End Tool', 'Lisle', 22.00, 70, 'Tools', 'https://example.com/images/tie-rod-tool.jpg'),
       ('Car Polish Compound', 'Meguiar’s', 18.99, 80, 'Chemicals', 'https://example.com/images/car-polish.jpg'),
       ('Bumper Fascia Push Pin', 'Dorman', 1.00, 500, 'Body', 'https://example.com/images/push-pin.jpg'),
       ('Wiper Blade Frame', 'Trico', 5.99, 150, 'Exterior', 'https://example.com/images/wiper-frame.jpg'),
       ('Heater Core Flush Kit', 'Prestone', 10.99, 90, 'HVAC', 'https://example.com/images/heater-flush-kit.jpg'),
       ('Door Latch Assembly', 'ACDelco', 75.00, 25, 'Body', 'https://example.com/images/door-latch.jpg'),
       ('Engine Valve Spring Compressor', 'Lisle', 40.00, 30, 'Tools',
        'https://example.com/images/valve-spring-compressor.jpg'),
       ('Brake Rotor Slotted', 'StopTech', 95.00, 45, 'Brakes', 'https://example.com/images/slotted-rotor.jpg'),
       ('License Plate Lock Screws', 'McGard', 15.00, 110, 'Accessories', 'https://example.com/images/lock-screws.jpg'),
       ('Fuel Filter Housing', 'Bosch', 65.00, 20, 'Fuel System', 'https://example.com/images/fuel-filter-housing.jpg'),
       ('Exhaust Pipe Reducer', 'Walker', 12.00, 130, 'Exhaust', 'https://example.com/images/pipe-reducer.jpg'),
       ('Oil Cooler Gasket Set', 'Victor Reinz', 18.00, 75, 'Engine',
        'https://example.com/images/oil-cooler-gasket.jpg'),
       ('Transmission Fluid Cooler Line', 'Dorman', 38.00, 55, 'Transmission',
        'https://example.com/images/cooler-line.jpg'),
       ('Suspension Sway Bar', 'Eibach', 150.00, 10, 'Suspension', 'https://example.com/images/sway-bar.jpg'),
       ('Brake Light Switch Connector', 'Dorman', 10.00, 120, 'Electrical',
        'https://example.com/images/light-switch-connector.jpg'),
       ('Tire Repair Patch', 'Slime', 5.00, 200, 'Tires', 'https://example.com/images/tire-patch.jpg'),
       ('Headlight Switch Knob', 'Dorman', 9.50, 90, 'Interior', 'https://example.com/images/headlight-knob.jpg'),
       ('Engine Oil Pressure Sensor Adapter', 'Blox Racing', 25.00, 60, 'Engine',
        'https://example.com/images/oil-sensor-adapter.jpg'),
       ('Steering Column Lock Housing', 'Dorman', 40.00, 35, 'Steering', 'https://example.com/images/lock-housing.jpg'),
       ('A/C Compressor Clutch Hub', 'Denso', 35.00, 40, 'HVAC', 'https://example.com/images/clutch-hub.jpg'),
       ('Brake Caliper Banjo Bolt', 'Dorman', 3.50, 300, 'Brakes', 'https://example.com/images/banjo-bolt.jpg'),
       ('Door Window Regulator Motor', 'ACDelco', 65.00, 30, 'Electrical',
        'https://example.com/images/regulator-motor.jpg'),
       ('Fuel Tank Vent Hose', 'Gates', 11.00, 150, 'Fuel System', 'https://example.com/images/vent-hose.jpg'),
       ('Radiator Cap Tester', 'Stant', 40.00, 50, 'Tools', 'https://example.com/images/radiator-cap-tester.jpg'),
       ('Body Panel Adhesive', '3M', 22.00, 75, 'Chemicals', 'https://example.com/images/panel-adhesive.jpg'),
       ('Wiper Arm Removal Tool', 'Lisle', 15.00, 90, 'Tools', 'https://example.com/images/wiper-arm-tool.jpg'),
       ('Engine Throttle Body Gasket', 'Fel-Pro', 5.99, 110, 'Engine',
        'https://example.com/images/throttle-body-gasket.jpg'),
       ('Differential Pinion Bearing', 'Timken', 35.00, 65, 'Drivetrain',
        'https://example.com/images/pinion-bearing.jpg'),
       ('Floor Mat Retainer Clip', 'Dorman', 2.00, 400, 'Interior', 'https://example.com/images/mat-clip.jpg'),
       ('Exhaust Gasket High Temp', 'Permatex', 8.99, 100, 'Chemicals',
        'https://example.com/images/high-temp-gasket.jpg'),
       ('Tailgate Cable', 'Dorman', 15.00, 80, 'Body', 'https://example.com/images/tailgate-cable.jpg'),
       ('Headlight Bulb H11', 'Sylvania', 12.99, 130, 'Lighting', 'https://example.com/images/headlight-bulb-h11.jpg'),
       ('Engine Oil Cooler Hose', 'Gates', 30.00, 55, 'Engine', 'https://example.com/images/oil-cooler-hose.jpg'),
       ('Brake Rotor Ceramic Coated', 'Centric', 80.00, 70, 'Brakes', 'https://example.com/images/ceramic-rotor.jpg'),
       ('A/C System O-Ring and Seal Kit', 'Four Seasons', 15.00, 95, 'HVAC',
        'https://example.com/images/o-ring-kit.jpg'),
       ('Tire Valve Core Remover', 'Slime', 3.00, 250, 'Tools', 'https://example.com/images/core-remover.jpg'),
       ('License Plate Security Fasteners', 'McGard', 18.00, 60, 'Accessories',
        'https://example.com/images/security-fasteners.jpg'),
       ('Steering Gear Box Seal Kit', 'Edelmann', 35.00, 40, 'Steering',
        'https://example.com/images/gear-box-seal-kit.jpg'),
       ('Engine Oil Change Sticker', 'Generic', 0.50, 500, 'Accessories', 'https://example.com/images/oil-sticker.jpg'),
       ('Transmission Main Shaft Seal', 'National', 8.50, 110, 'Transmission',
        'https://example.com/images/main-shaft-seal.jpg'),
       ('Wiper Blade Connector', 'Dorman', 4.00, 200, 'Exterior', 'https://example.com/images/wiper-connector.jpg'),
       ('Brake Caliper Piston Seal', 'Centric', 10.50, 150, 'Brakes', 'https://example.com/images/piston-seal.jpg'),
       ('Fuel Injector Pintle Cap', 'Bosch', 2.50, 300, 'Fuel System', 'https://example.com/images/pintle-cap.jpg'),
       ('Suspension Strut Top Mount', 'Moog', 45.00, 75, 'Suspension',
        'https://example.com/images/strut-top-mount.jpg'),
       ('Engine Oil Dipstick Handle', 'Dorman', 6.99, 100, 'Engine', 'https://example.com/images/dipstick-handle.jpg'),
       ('Exhaust Oxygen Sensor Extension', 'Blox Racing', 20.00, 65, 'Exhaust',
        'https://example.com/images/o2-extension.jpg'),
       ('Battery Terminal Protection Spray', 'CRC', 4.99, 140, 'Chemicals',
        'https://example.com/images/terminal-spray.jpg'),
       ('Door Glass Run Channel', 'Precision', 25.00, 50, 'Body', 'https://example.com/images/glass-run-channel.jpg'),
       ('Headlight Bulb 9005', 'Sylvania', 10.99, 120, 'Lighting',
        'https://example.com/images/headlight-bulb-9005.jpg'),
       ('A/C Pressure Switch', 'Standard', 30.00, 85, 'HVAC', 'https://example.com/images/ac-pressure-switch.jpg'),
       ('Tire Valve Stem Puller', 'Lisle', 9.50, 90, 'Tools', 'https://example.com/images/stem-puller.jpg'),
       ('Steering Intermediate Shaft', 'Dorman', 90.00, 25, 'Steering',
        'https://example.com/images/intermediate-shaft.jpg'),
       ('Engine Oil Drain Plug Magnetic', 'Mishimoto', 15.00, 70, 'Engine',
        'https://example.com/images/magnetic-drain-plug.jpg'),
       ('Brake Fluid Tester', 'OTC', 35.00, 45, 'Tools', 'https://example.com/images/brake-fluid-tester.jpg'),
       ('Console Organizer Tray', 'Dorman', 15.00, 60, 'Interior', 'https://example.com/images/organizer-tray.jpg'),
       ('Exhaust Clamp Band', 'Walker', 15.00, 110, 'Exhaust', 'https://example.com/images/clamp-band.jpg'),
       ('Fuel Line Repair Kit', 'Dorman', 25.00, 55, 'Fuel System',
        'https://example.com/images/fuel-line-repair-kit.jpg'),
       ('Suspension Sway Bar Link Kit', 'Moog', 35.00, 80, 'Suspension',
        'https://example.com/images/sway-bar-link-kit.jpg'),
       ('Timing Chain Guide Rail', 'Cloyes', 18.99, 70, 'Engine', 'https://example.com/images/guide-rail.jpg'),
       ('Transmission Oil Pan', 'Dorman', 55.00, 30, 'Transmission', 'https://example.com/images/trans-oil-pan.jpg'),
       ('Brake Line Coil', 'NiCopp', 15.00, 150, 'Brakes', 'https://example.com/images/brake-line-coil.jpg'),
       ('Engine Wiring Harness Connector', 'Dorman', 8.99, 120, 'Electrical',
        'https://example.com/images/wiring-connector.jpg'),
       ('Wiper Arm Black', 'ACDelco', 15.00, 95, 'Exterior', 'https://example.com/images/wiper-arm-black.jpg'),
       ('Headlight Bulb H13', 'Sylvania', 11.99, 100, 'Lighting', 'https://example.com/images/headlight-bulb-h13.jpg'),
       ('A/C Clutch Removal Tool', 'ACDelco', 40.00, 40, 'Tools', 'https://example.com/images/ac-clutch-tool.jpg'),
       ('Bumper Fascia Bolt', 'Dorman', 1.50, 300, 'Body', 'https://example.com/images/fascia-bolt.jpg'),
       ('Tire Gauge Analog', 'Accutire', 7.99, 180, 'Tires', 'https://example.com/images/analog-gauge.jpg'),
       ('Engine Throttle Body Cleaner', 'CRC', 6.50, 140, 'Chemicals',
        'https://example.com/images/throttle-cleaner.jpg'),
       ('Differential Fluid Pump', 'Lumax', 20.00, 60, 'Tools', 'https://example.com/images/diff-fluid-pump.jpg'),
       ('Power Steering Fluid Stop Leak', 'Lucas Oil', 12.99, 90, 'Chemicals',
        'https://example.com/images/ps-stop-leak.jpg'),
       ('Door Window Glass', 'TYC', 60.00, 25, 'Body', 'https://example.com/images/window-glass.jpg'),
       ('Exhaust Muffler Insulator', 'Dorman', 18.00, 70, 'Exhaust',
        'https://example.com/images/muffler-insulator.jpg'),
       ('Fuel Tank Filler Cap Tether', 'Dorman', 5.90, 110, 'Fuel System',
        'https://example.com/images/filler-cap-tether.jpg'),
       ('Suspension Alignment Camber Kit', 'Moog', 55.00, 35, 'Suspension',
        'https://example.com/images/camber-kit.jpg'),
       ('Engine Head Bolt Set', 'Fel-Pro', 45.00, 50, 'Engine', 'https://example.com/images/head-bolt-set.jpg'),
       ('Brake Caliper Brush Set', 'Lisle', 15.00, 80, 'Tools', 'https://example.com/images/caliper-brush.jpg'),
       ('License Plate Frame Novelty', 'Pilot', 14.99, 75, 'Accessories',
        'https://example.com/images/novelty-frame.jpg'),
       ('Wiper Fluid De-Icer', 'Prestone', 7.50, 130, 'Chemicals', 'https://example.com/images/wiper-de-icer.jpg'),
       ('A/C Compressor Oil', 'PAG 46', 15.00, 95, 'Oil & Fluids', 'https://example.com/images/ac-oil.jpg'),
       ('Tire Pressure Monitoring Tool', 'ATEQ', 150.00, 10, 'Tools', 'https://example.com/images/tpms-tool.jpg'),
       ('Steering Wheel Puller', 'OEM Tools', 30.00, 40, 'Tools', 'https://example.com/images/wheel-puller.jpg'),
       ('Engine Oil 15W-40 (Gallon)', 'Rotella', 25.00, 65, 'Oil & Fluids',
        'https://example.com/images/engine-oil-15w40.jpg'),
       ('Brake Rotor Drilled', 'Centric', 110.00, 50, 'Brakes', 'https://example.com/images/drilled-only-rotor.jpg'),
       ('Interior Dome Light Assembly', 'Dorman', 28.00, 60, 'Lighting',
        'https://example.com/images/dome-light-assembly.jpg'),
       ('Exhaust Gasket Copper', 'Fel-Pro', 9.99, 120, 'Exhaust', 'https://example.com/images/copper-gasket.jpg'),
       ('Fuel Filter Wrench', 'Lisle', 12.00, 90, 'Tools', 'https://example.com/images/fuel-filter-wrench.jpg'),
       ('Suspension Bushing Press Tool', 'OEM Tools', 85.00, 25, 'Tools',
        'https://example.com/images/bushing-press-tool.jpg'),
       ('Engine Valve Stem Seal Kit', 'Victor Reinz', 18.00, 80, 'Engine',
        'https://example.com/images/stem-seal-kit.jpg'),
       ('Transmission Shift Kit', 'TransGo', 80.00, 15, 'Transmission', 'https://example.com/images/shift-kit.jpg'),
       ('Battery Terminal Cover', 'Dorman', 3.00, 200, 'Electrical', 'https://example.com/images/terminal-cover.jpg'),
       ('Wiper Blade Beam', 'Bosch', 19.99, 100, 'Exterior', 'https://example.com/images/beam-wiper.jpg'),
       ('Door Panel Removal Tool', 'Lisle', 15.00, 110, 'Tools', 'https://example.com/images/panel-tool.jpg'),
       ('Bumper Mounting Bracket', 'TYC', 25.00, 70, 'Body', 'https://example.com/images/mounting-bracket.jpg'),
       ('Headlight Bulb 9006', 'Philips', 10.50, 150, 'Lighting', 'https://example.com/images/headlight-bulb-9006.jpg'),
       ('Engine Camshaft Follower', 'INA', 12.00, 95, 'Engine', 'https://example.com/images/camshaft-follower.jpg'),
       ('A/C Compressor Clutch Kit', 'Denso', 90.00, 30, 'HVAC', 'https://example.com/images/clutch-kit-ac.jpg'),
       ('Tire White Wall Cleaner', 'Westley’s', 7.50, 130, 'Chemicals',
        'https://example.com/images/white-wall-cleaner.jpg'),
       ('Brake Drum Puller', 'OEM Tools', 45.00, 40, 'Tools', 'https://example.com/images/drum-puller.jpg'),
       ('Exhaust Manifold Hardware Kit', 'Dorman', 15.00, 75, 'Exhaust',
        'https://example.com/images/manifold-hardware.jpg'),
       ('Fuel Tank Sending Unit Seal', 'Fel-Pro', 6.50, 120, 'Fuel System',
        'https://example.com/images/sending-unit-seal.jpg'),
       ('Steering Shaft Lower', 'Dorman', 70.00, 20, 'Steering', 'https://example.com/images/steering-shaft-lower.jpg'),
       ('Oil Filter End Cap Wrench', 'Lisle', 8.50, 100, 'Tools', 'https://example.com/images/filter-cap-wrench.jpg'),
       ('Suspension Strut Cartridge', 'KYB', 60.00, 55, 'Suspension', 'https://example.com/images/strut-cartridge.jpg'),
       ('Engine Oil Full Synthetic (Quart)', 'Mobil 1', 10.99, 250, 'Oil & Fluids',
        'https://example.com/images/full-synth-oil.jpg'),
       ('Transmission Filter Kit Deep Pan', 'Wix', 45.00, 65, 'Transmission',
        'https://example.com/images/deep-pan-filter-kit.jpg'),
       ('Brake Fluid DOT 5.1', 'ATE', 18.00, 150, 'Brakes', 'https://example.com/images/brake-fluid-dot5.jpg'),
       ('Jumper Cable Clamp', 'BoostAll', 5.00, 300, 'Electrical', 'https://example.com/images/clamp-jumper.jpg'),
       ('Tail Light Gasket', 'Dorman', 10.50, 90, 'Lighting', 'https://example.com/images/tail-light-gasket.jpg'),
       ('Warning Triangle 571', 'RoadSafe', 370.78, 198, 'Safety',
        'https://example.com/images/warning-triangle-571.jpg'),
       ('Fire Extinguisher 584', 'RoadSafe', 69.41, 111, 'Safety',
        'https://example.com/images/fire-extinguisher-584.jpg'),
       ('Warning Triangle 537', 'SafeRide', 157.71, 10, 'Safety',
        'https://example.com/images/warning-triangle-537.jpg'),
       ('Seat Belt Cutter 511', 'Guardian', 45.53, 37, 'Safety', 'https://example.com/images/seat-belt-cutter-511.jpg'),
       ('First Aid Kit 505', 'Guardian', 37.98, 116, 'Safety', 'https://example.com/images/first-aid-kit-505.jpg'),
       ('Safety Vest 518', 'RoadSafe', 273.74, 53, 'Safety', 'https://example.com/images/safety-vest-518.jpg'),
       ('Warning Triangle 567', 'SafeRide', 103.88, 153, 'Safety',
        'https://example.com/images/warning-triangle-567.jpg'),
       ('Fire Extinguisher 596', 'Guardian', 338.48, 143, 'Safety',
        'https://example.com/images/fire-extinguisher-596.jpg'),
       ('Seat Belt Cutter 575', 'SafeRide', 156.91, 104, 'Safety',
        'https://example.com/images/seat-belt-cutter-575.jpg'),
       ('First Aid Kit 554', 'RoadSafe', 290.38, 160, 'Safety', 'https://example.com/images/first-aid-kit-554.jpg'),
       ('Safety Vest 507', 'Guardian', 40.58, 28, 'Safety', 'https://example.com/images/safety-vest-507.jpg'),
       ('Warning Triangle 552', 'RoadSafe', 148.80, 22, 'Safety',
        'https://example.com/images/warning-triangle-552.jpg'),
       ('Fire Extinguisher 505', 'SafeRide', 43.15, 78, 'Safety',
        'https://example.com/images/fire-extinguisher-505.jpg'),
       ('Seat Belt Cutter 538', 'Guardian', 320.12, 187, 'Safety',
        'https://example.com/images/seat-belt-cutter-538.jpg'),
       ('First Aid Kit 510', 'RoadSafe', 80.05, 93, 'Safety', 'https://example.com/images/first-aid-kit-510.jpg'),
       ('Safety Vest 532', 'SafeRide', 160.05, 14, 'Safety', 'https://example.com/images/safety-vest-532.jpg'),
       ('Warning Triangle 543', 'Guardian', 253.28, 196, 'Safety',
        'https://example.com/images/warning-triangle-543.jpg'),
       ('Fire Extinguisher 555', 'RoadSafe', 167.92, 172, 'Safety',
        'https://example.com/images/fire-extinguisher-555.jpg'),
       ('Seat Belt Cutter 561', 'SafeRide', 156.40, 10, 'Safety',
        'https://example.com/images/seat-belt-cutter-561.jpg'),
       ('First Aid Kit 569', 'Guardian', 455.08, 19, 'Safety', 'https://example.com/images/first-aid-kit-569.jpg'),
       ('Safety Vest 586', 'RoadSafe', 423.51, 158, 'Safety', 'https://example.com/images/safety-vest-586.jpg'),
       ('Warning Triangle 598', 'SafeRide', 246.06, 21, 'Safety',
        'https://example.com/images/warning-triangle-598.jpg'),
       ('Fire Extinguisher 589', 'Guardian', 391.20, 161, 'Safety',
        'https://example.com/images/fire-extinguisher-589.jpg'),
       ('Seat Belt Cutter 544', 'RoadSafe', 327.95, 128, 'Safety',
        'https://example.com/images/seat-belt-cutter-544.jpg'),
       ('First Aid Kit 590', 'SafeRide', 459.76, 32, 'Safety', 'https://example.com/images/first-aid-kit-590.jpg'),
       ('Safety Vest 501', 'Guardian', 412.33, 114, 'Safety', 'https://example.com/images/safety-vest-501.jpg'),
       ('Warning Triangle 563', 'RoadSafe', 70.38, 112, 'Safety',
        'https://example.com/images/warning-triangle-563.jpg'),
       ('Fire Extinguisher 539', 'SafeRide', 342.34, 110, 'Safety',
        'https://example.com/images/fire-extinguisher-539.jpg'),
       ('Seat Belt Cutter 587', 'Guardian', 421.49, 14, 'Safety',
        'https://example.com/images/seat-belt-cutter-587.jpg'),
       ('First Aid Kit 530', 'RoadSafe', 400.93, 137, 'Safety', 'https://example.com/images/first-aid-kit-530.jpg'),
       ('Safety Vest 525', 'SafeRide', 194.27, 24, 'Safety', 'https://example.com/images/safety-vest-525.jpg'),
       ('Warning Triangle 583', 'Guardian', 270.36, 172, 'Safety',
        'https://example.com/images/warning-triangle-583.jpg'),
       ('Fire Extinguisher 506', 'RoadSafe', 77.29, 21, 'Safety',
        'https://example.com/images/fire-extinguisher-506.jpg'),
       ('Seat Belt Cutter 502', 'SafeRide', 211.75, 19, 'Safety',
        'https://example.com/images/seat-belt-cutter-502.jpg'),
       ('First Aid Kit 574', 'Guardian', 121.78, 142, 'Safety', 'https://example.com/images/first-aid-kit-574.jpg'),
       ('Safety Vest 528', 'RoadSafe', 193.38, 59, 'Safety', 'https://example.com/images/safety-vest-528.jpg'),
       ('Warning Triangle 590', 'SafeRide', 386.95, 87, 'Safety',
        'https://example.com/images/warning-triangle-590.jpg'),
       ('Fire Extinguisher 548', 'Guardian', 374.92, 176, 'Safety',
        'https://example.com/images/fire-extinguisher-548.jpg'),
       ('Seat Belt Cutter 570', 'RoadSafe', 387.64, 55, 'Safety',
        'https://example.com/images/seat-belt-cutter-570.jpg'),
       ('First Aid Kit 599', 'SafeRide', 120.37, 139, 'Safety', 'https://example.com/images/first-aid-kit-599.jpg'),
       ('Safety Vest 593', 'Guardian', 443.43, 13, 'Safety', 'https://example.com/images/safety-vest-593.jpg'),
       ('Warning Triangle 597', 'RoadSafe', 279.79, 153, 'Safety',
        'https://example.com/images/warning-triangle-597.jpg'),
       ('Fire Extinguisher 594', 'SafeRide', 113.88, 149, 'Safety',
        'https://example.com/images/fire-extinguisher-594.jpg'),
       ('Seat Belt Cutter 547', 'Guardian', 328.79, 162, 'Safety',
        'https://example.com/images/seat-belt-cutter-547.jpg'),
       ('First Aid Kit 539', 'RoadSafe', 218.41, 190, 'Safety', 'https://example.com/images/first-aid-kit-539.jpg'),
       ('Safety Vest 545', 'SafeRide', 201.21, 108, 'Safety', 'https://example.com/images/safety-vest-545.jpg'),
       ('Warning Triangle 585', 'Guardian', 106.31, 20, 'Safety',
        'https://example.com/images/warning-triangle-585.jpg'),
       ('Fire Extinguisher 524', 'RoadSafe', 357.51, 71, 'Safety',
        'https://example.com/images/fire-extinguisher-524.jpg'),
       ('Seat Belt Cutter 535', 'SafeRide', 248.87, 107, 'Safety',
        'https://example.com/images/seat-belt-cutter-535.jpg'),
       ('First Aid Kit 526', 'Guardian', 381.56, 177, 'Safety', 'https://example.com/images/first-aid-kit-526.jpg'),
       ('Safety Vest 577', 'RoadSafe', 319.49, 11, 'Safety', 'https://example.com/images/safety-vest-577.jpg'),
       ('Warning Triangle 529', 'SafeRide', 47.78, 101, 'Safety',
        'https://example.com/images/warning-triangle-529.jpg'),
       ('Fire Extinguisher 530', 'Guardian', 438.16, 50, 'Safety',
        'https://example.com/images/fire-extinguisher-530.jpg'),
       ('Seat Belt Cutter 517', 'RoadSafe', 202.82, 106, 'Safety',
        'https://example.com/images/seat-belt-cutter-517.jpg'),
       ('First Aid Kit 565', 'SafeRide', 140.24, 13, 'Safety', 'https://example.com/images/first-aid-kit-565.jpg'),
       ('Safety Vest 594', 'Guardian', 387.89, 78, 'Safety', 'https://example.com/images/safety-vest-594.jpg'),
       ('Warning Triangle 551', 'RoadSafe', 231.11, 46, 'Safety',
        'https://example.com/images/warning-triangle-551.jpg'),
       ('Fire Extinguisher 543', 'SafeRide', 28.53, 50, 'Safety',
        'https://example.com/images/fire-extinguisher-543.jpg'),
       ('Seat Belt Cutter 592', 'Guardian', 242.02, 12, 'Safety',
        'https://example.com/images/seat-belt-cutter-592.jpg'),
       ('First Aid Kit 582', 'RoadSafe', 389.96, 171, 'Safety', 'https://example.com/images/first-aid-kit-582.jpg'),
       ('Safety Vest 503', 'SafeRide', 338.45, 142, 'Safety', 'https://example.com/images/safety-vest-503.jpg'),
       ('Warning Triangle 520', 'Guardian', 385.08, 187, 'Safety',
        'https://example.com/images/warning-triangle-520.jpg'),
       ('Fire Extinguisher 515', 'RoadSafe', 144.11, 23, 'Safety',
        'https://example.com/images/fire-extinguisher-515.jpg'),
       ('Seat Belt Cutter 573', 'SafeRide', 170.85, 200, 'Safety',
        'https://example.com/images/seat-belt-cutter-573.jpg'),
       ('First Aid Kit 503', 'Guardian', 33.74, 98, 'Safety', 'https://example.com/images/first-aid-kit-503.jpg'),
       ('Safety Vest 504', 'RoadSafe', 204.09, 137, 'Safety', 'https://example.com/images/safety-vest-504.jpg'),
       ('Warning Triangle 546', 'SafeRide', 280.95, 185, 'Safety',
        'https://example.com/images/warning-triangle-546.jpg'),
       ('Fire Extinguisher 578', 'Guardian', 363.64, 150, 'Safety',
        'https://example.com/images/fire-extinguisher-578.jpg'),
       ('Seat Belt Cutter 525', 'RoadSafe', 211.85, 127, 'Safety',
        'https://example.com/images/seat-belt-cutter-525.jpg'),
       ('First Aid Kit 562', 'SafeRide', 110.15, 166, 'Safety', 'https://example.com/images/first-aid-kit-562.jpg'),
       ('Safety Vest 598', 'Guardian', 350.29, 133, 'Safety', 'https://example.com/images/safety-vest-598.jpg'),
       ('Warning Triangle 580', 'RoadSafe', 327.91, 14, 'Safety',
        'https://example.com/images/warning-triangle-580.jpg'),
       ('Fire Extinguisher 546', 'SafeRide', 374.05, 50, 'Safety',
        'https://example.com/images/fire-extinguisher-546.jpg'),
       ('Seat Belt Cutter 516', 'Guardian', 438.22, 194, 'Safety',
        'https://example.com/images/seat-belt-cutter-516.jpg'),
       ('First Aid Kit 540', 'RoadSafe', 356.54, 73, 'Safety', 'https://example.com/images/first-aid-kit-540.jpg'),
       ('Safety Vest 541', 'SafeRide', 346.99, 18, 'Safety', 'https://example.com/images/safety-vest-541.jpg'),
       ('Warning Triangle 505', 'Guardian', 201.78, 30, 'Safety',
        'https://example.com/images/warning-triangle-505.jpg'),
       ('Fire Extinguisher 523', 'RoadSafe', 353.97, 10, 'Safety',
        'https://example.com/images/fire-extinguisher-523.jpg'),
       ('Seat Belt Cutter 576', 'SafeRide', 450.04, 88, 'Safety',
        'https://example.com/images/seat-belt-cutter-576.jpg'),
       ('First Aid Kit 568', 'Guardian', 41.52, 156, 'Safety', 'https://example.com/images/first-aid-kit-568.jpg'),
       ('Safety Vest 514', 'RoadSafe', 472.08, 169, 'Safety', 'https://example.com/images/safety-vest-514.jpg'),
       ('Warning Triangle 558', 'SafeRide', 442.22, 199, 'Safety',
        'https://example.com/images/warning-triangle-558.jpg'),
       ('Fire Extinguisher 514', 'Guardian', 104.22, 114, 'Safety',
        'https://example.com/images/fire-extinguisher-514.jpg'),
       ('Seat Belt Cutter 550', 'RoadSafe', 428.18, 162, 'Safety',
        'https://example.com/images/seat-belt-cutter-550.jpg'),
       ('First Aid Kit 513', 'SafeRide', 371.82, 28, 'Safety', 'https://example.com/images/first-aid-kit-513.jpg'),
       ('Safety Vest 510', 'Guardian', 179.62, 112, 'Safety', 'https://example.com/images/safety-vest-510.jpg'),
       ('Warning Triangle 506', 'RoadSafe', 142.13, 109, 'Safety',
        'https://example.com/images/warning-triangle-506.jpg'),
       ('Fire Extinguisher 593', 'SafeRide', 484.51, 194, 'Safety',
        'https://example.com/images/fire-extinguisher-593.jpg'),
       ('Seat Belt Cutter 590', 'Guardian', 42.66, 171, 'Safety',
        'https://example.com/images/seat-belt-cutter-590.jpg'),
       ('First Aid Kit 594', 'RoadSafe', 153.90, 75, 'Safety', 'https://example.com/images/first-aid-kit-594.jpg'),
       ('Safety Vest 505', 'SafeRide', 47.98, 112, 'Safety', 'https://example.com/images/safety-vest-505.jpg'),
       ('Warning Triangle 559', 'Guardian', 371.97, 148, 'Safety',
        'https://example.com/images/warning-triangle-559.jpg'),
       ('Fire Extinguisher 509', 'RoadSafe', 308.06, 196, 'Safety',
        'https://example.com/images/fire-extinguisher-509.jpg'),
       ('Seat Belt Cutter 588', 'SafeRide', 115.65, 14, 'Safety',
        'https://example.com/images/seat-belt-cutter-588.jpg'),
       ('First Aid Kit 589', 'Guardian', 319.46, 10, 'Safety', 'https://example.com/images/first-aid-kit-589.jpg'),
       ('Safety Vest 564', 'RoadSafe', 386.42, 118, 'Safety', 'https://example.com/images/safety-vest-564.jpg'),
       ('Warning Triangle 584', 'SafeRide', 290.41, 10, 'Safety',
        'https://example.com/images/warning-triangle-584.jpg'),
       ('Fire Extinguisher 537', 'Guardian', 157.71, 10, 'Safety',
        'https://example.com/images/fire-extinguisher-537.jpg'),
       ('Seat Belt Cutter 511', 'RoadSafe', 45.53, 37, 'Safety', 'https://example.com/images/seat-belt-cutter-511.jpg');
INSERT INTO users (name, email, password_hash)
VALUES ('test', 'test@example.com', '$2b$10$o5fKoObdV5BeVZOvSEj3He/LOO1pkkNgzfUHSSwIJh.uR.lqhES8i');