version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: autoparts-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoparts_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_autoparts_data:/var/lib/mysql
    networks:
      - autoparts-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DATABASE_URL: mysql://root:root@mysql:3306/autoparts_db
    container_name: autoparts-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: mysql://root:root@mysql:3306/autoparts_db
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 3600
      FRONTEND_URL: http://localhost:3000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - autoparts-network

volumes:
  mysql_autoparts_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './mysql_docker_data'

networks:
  autoparts-network:
    driver: bridge